[Feat/#13] 카카오 검색과 구글 지도 추가
Nexters/JYP-iOS pull request #14
Opened 2022-07-26 08:30 UTC by mooyoung2309

## PR 요약
여행 후보 장소 검색 입니다. 
GOOGLE_APP_KEY가 추가되었고, 저한테 카톡 주시면 드리겠습니닷.
패턴 적용은 아직이고, 일단 돌아가는 뷰를 짰고 이후에 패턴을 협의 후에 적용시켜나가겠습니다.

몇가지 이슈가 있어 코멘트로 정리 하겠습니다.

#### 📌 변경 사항
검색은 카카오 API를 사용했습니다.
지도는 구글 맵을 사용했습니다.

##### ✅ PR check list
1. NavigationBar을 커스텀하고 있는데, Reusable이라는 폴더 안에 집어 넣었습니다. 구현 아이디어를 구상중에 있습니다. 피드백 받습니다. (목요일날 얘기 가능)
2. 검색 부분에서 인애누님이 만드신 코드를 그대로 가져다 썼는데, 피드백 부탁드립니다 !

#### Linked Issue

close #13

2022-07-26 08:45 UTC, mooyoung2309 commented
## GoogleMaps가 코코아팟, 카르타고만 지원함.
해결 시도한 방법은 두가지였는데
1. carthage 사용
카르타고를 사용했을때, Tuist에서 오류인지 정확히 확인을 하지는 못했지만, GoogleMaps만 다운로드가 안되었습니다. 다른 것들(RxSwift, SnapKit 이런것들)을 카르타고로 했을때는 문제가 없었지만, fetch 속도가 너무 느려지는 문제를 발견했습니다. SPM에 거의 10배 이상 느려짐. 그리고 SPM과 카르타고를 섞어서 사용하는 방식을 고려하였지만, 역시 GoogleMaps를 다운하는데는 실패했습니다.
3. 우회 SPM 사용
https://github.com/YAtechnologies/GoogleMaps-SP
우선은 위의 우회 SPM 다운로드 깃허브 주소에서 최신 버전의 GoogleMaps를 다운로드 하는 것에 성공했습니다. 하지만, 폴더 경로가 Tuist 설정한 것처럼 잘 들어가지는 않았습니다. 우선은 해결한 상태이고, 추가적으로 카르타고를 다운하는 방식을 좀 더 연구해보겠습니다. (심신미약.)

## M1 칩을 사용했을 때 시뮬레이터에서 GoogleMaps 사용 에러
이건 아직 해결을 못했습니다. 그리고 앞으로도 해결을 할 수 있을지 의문입니다. 우회적으로 해결한 방법은 맥 OS로 빌드를 했을 때는 잘 돌아갔습니다. 아마도 실제 디바이스로도 문제가 없을거로 예상됩니다. (제 컴에서 디바이스 연결이 안됨. 어제 얘기한 내용)
1. exclude architexture에 arm64추가하기 -> 걍 터짐
2. 로제타로 실행 -> 이거는 너무 느려지고 잘 안됐음.

2022-07-27 14:53 UTC, leeinae requested changes

2022-07-27 14:53 UTC, leeinae commented on JYP-iOS/JYP-iOS/Sources/Presenter/SearchPlace/Component/SearchPlaceResultTableViewCell.swift
> +    static let id = "SearchPlaceResultTableViewCell"
static let 으로 identifier를 지정하지 않고, class의 타입명 (클래스 이름)으로 identifier를 지정하는 방법도 있습니다!

`String(describing: SearchPlaceResultTableViewCell.self)`

저는 해당 코드를 `.register` 함수의 argument로 넣어 사용하고 있습니닷. 이 방식의 장점은 클래스 명이 바뀌어도 identifier를 일일이 변경할 필요가 없어집니다 :>

2022-07-27 14:53 UTC, leeinae commented on JYP-iOS/JYP-iOS/Sources/Presenter/SearchPlace/Component/SearchPlaceResultTableViewCell.swift
> +        titleLabel.font = .systemFont(ofSize: 16)
그냥 질문) Then 라이브러리는 잘 안쓰시는 편이신가옹

2022-07-27 14:53 UTC, leeinae commented on JYP-iOS/JYP-iOS/Sources/Presenter/SearchPlace/Component/SearchPlaceView.swift
> +import UIKit
트집 아님) UIKit 안에 Foundation이 포함되어 있어서 UIKit만 import 해주어도 될 것 같습니다!

2022-07-27 14:53 UTC, leeinae commented on JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/NavigationBar.swift
> +    let backButton = UIButton(type: .system)
버튼에 액션은 어떻게 처리하는 게 좋을지 고민되네요 ~ 👀

2022-07-27 14:53 UTC, leeinae commented on JYP-iOS/JYP-iOS/Sources/Presenter/SearchPlace/SearchPlaceViewController.swift
> +        navigationContentView.searchTextField.rx.text.orEmpty
```suggestion
        navigationContentView.searchTextField.rx.text.orEmpty
            .distinctUntilChanged()
            .debounce(.milliseconds(500), scheduler: MainScheduler.instance)
```

2022-07-27 14:53 UTC, leeinae commented on JYP-iOS/JYP-iOS/Sources/Presenter/SearchPlace/SearchPlaceViewController.swift
> +        navigationContentView.searchTextField.rx.text.orEmpty
해당 로직에 `debounce`를 걸어서 여러 개의 입력이 들어오는 중에 가장 마지막 이벤트를 방출할 수 있도록 해야할 것 같습니다 ..! 
그렇지 않으면 입력 때마다 불필요한 네트워크 호출의 여지가 있습니다.

2022-07-27 14:53 UTC, leeinae commented on Project.swift
> +
해당 부분 혹시 테스트 용도라면 삭제 부탁드립니다! 나중에 부활할 여지가 있다면 남겨두셔도 좋을 것 같습니다.

2022-07-27 14:53 UTC, leeinae commented on Tuist/Dependencies.swift
> +    .binary(path: "https://dl.google.com/geosdk/GoogleMaps.json", requirement: .upToNext("6.0.0")),
아 카르타고 도전 중이셨군요..

2022-07-27 14:53 UTC, leeinae commented
어려운 뷰를 아주 .. 빠르게 .. 개발해주셨군요 .. 최고입니다 .. 👍

2022-07-28 12:35 UTC, mooyoung2309 commented on JYP-iOS/JYP-iOS/Sources/Presenter/SearchPlace/Component/SearchPlaceResultTableViewCell.swift
> +    static let id = "SearchPlaceResultTableViewCell"
좋은 정보 감사합니닷 . . ! 수정 완료했습니다

2022-07-28 12:36 UTC, annapo99 commented on JYP-iOS/JYP-iOS/Sources/Presenter/SearchPlace/Component/SearchPlaceResultTableViewCell.swift
> +        titleLabel.font = .systemFont(ofSize: 16)
처음에 잘 썼는데 선언부 부분이 너무 길어져서 어떤 컴포넌트가 있는지 헷갈려서 가독성이 떨어진다고 스스로 판단해서 setupProperty에서 전부다 넣는 형식으로 개발하게 되었습니다 . . !

2022-07-28 12:36 UTC, mooyoung2309 commented on JYP-iOS/JYP-iOS/Sources/Presenter/SearchPlace/Component/SearchPlaceView.swift
> +import UIKit
요것도 반영 완료했습니다 !

2022-07-28 12:41 UTC, mooyoung2309 commented on Project.swift
> +
해당 부분 나중에 부활할 여지가 10퍼센트 정도 ? (거의없긴함) 시도해보는 중이었습니다 !

2022-07-28 12:41 UTC, mooyoung2309 commented on Tuist/Dependencies.swift
> +    .binary(path: "https://dl.google.com/geosdk/GoogleMaps.json", requirement: .upToNext("6.0.0")),
카르타고는 속도가 너무 느리다는 단점이 있는데, 우선은 됐으니깐 일단 넘어가겠습니다 . . !

2022-07-28 12:45 UTC, leeinae approved these changes

2022-07-28 12:45 UTC, merged