[Feat/#16] 공통 네비게이션 바 구현
Nexters/JYP-iOS pull request #20
Opened 2022-07-30 15:10 UTC by mooyoung2309

## PR 요약
공통 네비게이션 바 구현입니다.
초록색 부분이 상태바, 파란색 부분이 네비게이션 바, 핑크색이 컨텐츠 뷰입니다.
앞으로 네비게이션바가 필요한 뷰 컨트롤러에서는 NavigationBarController을 상속 받고 setupNavigationBar 함수 안에서 네비게이션 관련 세팅을 해놓고 사용하면 됩니다 ! (인애누나의 바텀 시트 아이디어 참고함.)
상태바와 네비게이션 바의 색상은 똑같이 변경되도록 구현하였습니다.

BaseNavigationBarViewControllerProtocol을 상속 받고 있으면 해당 프로토콜안에 외부에서 호출할 함수를 정의 하였습니다.
백 버튼을 숨길수도 있고 등등 이 있는데, 사용해보면서 필요하다 싶은 것들을 추가하겠습니다.

#### 📌 변경 사항
<img width="299" alt="image" src="https://user-images.githubusercontent.com/77970826/181920308-59e72906-55f0-40d9-8212-b279a604c8bc.png">

##### ✅ PR check list
추가적으로 재사용 버튼 구현중에 있는데, 좀 더 좋게 짜려고 노력 중에 있습니다.

#### Linked Issue

close #16

2022-07-31 14:05 UTC, leeinae requested changes

2022-07-31 14:05 UTC, leeinae commented on JYP-iOS/JYP-iOS/Sources/Presenter/NavigationBar/NavigationBarViewController.swift
> +class NavigationBarViewController: BaseViewController, BaseNavigationBarViewControllerProtocol {
해당 클래스를 상속받아서 뷰컨을 만들어야하는 것으로 이해했는데, 외부에서 수정할 일이 적다면 Base 폴더로 옮기는 건 어떨까요?

2022-07-31 14:05 UTC, leeinae commented on JYP-iOS/JYP-iOS/Sources/Presenter/NavigationBar/NavigationBarViewController.swift
> +    var navigaionBar: NavigationBar { get }
오타가 있는 것 같습니다~! gation에 t 누락쓰 ㅋ ㅋ

2022-07-31 14:05 UTC, leeinae commented on JYP-iOS/JYP-iOS/Sources/Presenter/OnBoarding/OnboardingView.swift
> +class OnboardingView: BaseView {
이 클래스는 어떤 용도로 사용되나요?

2022-07-31 14:05 UTC, leeinae commented on JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPButton.swift
> +            backgroundColor = isSelected ? type.inactiveConfig.backgroundColor : type.activeConfig?.backgroundColor
버튼색이 변경되는 케이스를 보면 버튼의 선택 여부보다는 현재 해당 버튼 활성화로 생각되는데, `isSelected` 속성보다 `isEnabled`로 제어하는 건 어떨까요?
isEnabled로 제어한다면 비활성화 일 때 버튼이 눌리지 않도록 하는 처리도 가능하니 해당 기능에 더 적합할 것이라고 생각합니다!

2022-07-31 14:05 UTC, leeinae commented on JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPButton.swift
> +            backgroundColor = isSelected ? type.inactiveConfig.backgroundColor : type.activeConfig?.backgroundColor
그렇게 변경되면 삼항 연산자의 true false 값도 서로 변경되어야 할 것 같습니다~!

2022-07-31 14:05 UTC, leeinae commented on JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPButton.swift
> +    var inactiveConfig: JYPButtonConfig {
inactive, active를 분리해서 관리하는 것은 좋은 아이디어 같습니다! 
혹시 title도 active값에 의존성을 가지는 이유가 있을까요? 

```swift
    var title: String {
        switch self {
        case .next:
            return "다음으로"
        case .done:
            return "완료하기"
        case .start:
            return "시작하기"
        case .startPlan:
            return "여행 계획 시작하기"
        case .add:
            return "추가하기"
        case .smallAdd:
            return "시작하기"
        case .smallMake:
            return "만들기"
        case .yes:
            return "좋아요"
        case .no:
            return "싫어요"
        }
    }

```

title값을 분리해서 중복되는 값을 줄이는 방법도 있을 것 같습니다. (하지만 활성, 비활 여부에 따라서 titleLabel이 달라진다면 영모 코드가 더 적합할 것 같네요!!)

2022-07-31 14:05 UTC, leeinae commented on JYP-iOS/JYP-iOS/Sources/Presenter/NavigationBar/NavigationBarViewController.swift
> +
```suggestion

    override func setupBind() {
        navigaionBar.backButton.rx.tap
            .bind { [weak self] _ in
                self?.navigationController?.popViewController(animated: true)
            }
            .disposed(by: disposeBag)
    }


```

해당 클래스에서 backButton bind를 해주는 건 어떨까요?

2022-07-31 14:05 UTC, leeinae commented on JYP-iOS/JYP-iOS/Sources/Presenter/NavigationBar/NavigationBarViewController.swift
> +        navigationController?.setNavigationBarHidden(true, animated: false)
```suggestion
        navigationController?.setNavigationBarHidden(true, animated: false)
        navigationController?.interactivePopGestureRecognizer?.delegate = nil
```

navigationBar가 hidden일 때는 스와이프 백 제스처가 동작하지 않아 아래와 같은 처리가 필요하다고 생각합니다

2022-07-31 14:05 UTC, leeinae commented on JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPButton.swift
> +class JYPButton: UIButton {
develop 브랜치 pull 받으셔서 버튼에 `shadow` 및 스타일 적용 부탁드립니다! 해당 내용은 navigation Bar도 동일합니다.

2022-07-31 14:05 UTC, leeinae commented on JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPButton.swift
> +        layer.cornerRadius = 12
이것도 UIView에 있는 extension 함수로 변경 부탁드립니다!

2022-07-31 14:05 UTC, leeinae commented on JYP-iOS/JYP-iOS/Sources/Presenter/NavigationBar/NavigationBarViewController.swift
> +    func setNavigationBarTitleFont(_ font: UIFont?)
titleColor, text, font 속성을 각각 따로 지정하는 이유가 있나요? 한 함수에서 arguments로 받아서 관리해도 될 것 같다는 생각이 들어서 ...

2022-07-31 15:51 UTC, mooyoung2309 commented on JYP-iOS/JYP-iOS/Sources/Presenter/NavigationBar/NavigationBarViewController.swift
> +    var navigaionBar: NavigationBar { get }
오 ㅎㅎ 감사합니닷 !

2022-08-01 16:46 UTC, mooyoung2309 commented on JYP-iOS/JYP-iOS/Sources/Presenter/OnBoarding/OnboardingView.swift
> +class OnboardingView: BaseView {
테스트 용으로 남겨놨었는데 삭제완료 했습니다 !

2022-08-01 16:58 UTC, mooyoung2309 commented on JYP-iOS/JYP-iOS/Sources/Presenter/NavigationBar/NavigationBarViewController.swift
> +
굿 아이디어 ,, 반영완료 했습니다 ~ !

2022-08-01 17:00 UTC, mooyoung2309 commented on JYP-iOS/JYP-iOS/Sources/Presenter/NavigationBar/NavigationBarViewController.swift
> +        navigationController?.setNavigationBarHidden(true, animated: false)
[공식 문서](https://developer.apple.com/documentation/uikit/uinavigationcontroller/1621847-interactivepopgesturerecognizer)
[이슈 예시](https://borabong.tistory.com/14)

학습 완, 반영 완료했습니다 ! 감사합니당

2022-08-01 17:02 UTC, mooyoung2309 commented on JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPButton.swift
> +class JYPButton: UIButton {
develop 브랜치에 풀을 받았는데, 전에 분명히 설명해주셨었는데, 작업 도중에 풀받아도 되는거 확인했었는데, 저는 왜 혼자서는 못할까요 ㅡ , , 이거 내일 다시 여쭤보겠습니다. 일단은 섀도우랑 라운딩 다음에 추가하는걸로 해도 될까요 . . ?

2022-08-01 17:02 UTC, mooyoung2309 commented on JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPButton.swift
> +        layer.cornerRadius = 12
// TODO: 내일 말씀 드리기

2022-08-01 17:07 UTC, mooyoung2309 commented on JYP-iOS/JYP-iOS/Sources/Presenter/NavigationBar/NavigationBarViewController.swift
> +    func setNavigationBarTitleFont(_ font: UIFont?)
원래는, 함수를 분리 시키는게 습관이어서 , , 이렇게 하면 좋을거라 판단했습니다.

+ 살짝 이유를 붙여보자면, 색과 폰트는 변경되는 일이 거의 없고, 보통은 텍스트만 바뀌어서 텍스트만 바꾸는 함수를 작성했는데, 후에 네비게이션 바에 폰트랑 색상이 변경되는 케이스를 확인해서 이렇게 짰습니닷.

2022-08-01 17:08 UTC, mooyoung2309 commented on JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPButton.swift
> +    var inactiveConfig: JYPButtonConfig {
UI를 전부 찾아보니깐, title값은 고정으로 해도 될 것 같습니다. . ! 앞으로도 변경될일은 없어보입니다 ! 반영 완료했습니다 . !

2022-08-01 17:10 UTC, annapo99 commented on JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPButton.swift
> +            backgroundColor = isSelected ? type.inactiveConfig.backgroundColor : type.activeConfig?.backgroundColor
좋은 리뷰 감사합니다 , , 이부분 반영완료 했습니다 . . ! 

`isEnabled`값이 true 이면 활성화(핑크색) 상태, false 이면 비활성화(어두침침) 상태입니다 !

2022-08-01 17:10 UTC, annapo99 commented on JYP-iOS/JYP-iOS/Sources/Presenter/NavigationBar/NavigationBarViewController.swift
> +class NavigationBarViewController: BaseViewController, BaseNavigationBarViewControllerProtocol {
옮김 완료했습니닷 !

2022-08-01 17:31 UTC, mooyoung2309 commented
# ReactorKit 예시 요약
## 예시 상황 설명
onboardingLiking 뷰컨의 nextbutton을 누르면 onboardingPlace 뷰컨으로 화면 전환

## Reactor 단위
하나의 뷰컨당 하나의 Reactor을 생성하는 것으로 합니다. 
뷰컨에서는 View를 상속받고
Reactor에서는 Reactor을 상속받아서 구현합니다.

```swift
class OnboardingLikingViewController: NavigationBarViewController, View {
    typealias Reactor = OnboardingLikingReactor
    ...
}

class OnboardingLikingReactor: Reactor {  
    ....
}
```

## 의존성 주입
0. A(ViewController) -> B(ViewController) 로 화면 전환 상황
1. A에서 B의 Reactor 생성
2. A에서 B의 Reactor 주입 후 화면 전환

B의 Reactor init 부분에서 A에게 의존성을 받을 수 있도록 변경 해야함


```swift
// MARK: OnboardingLikingReactor

extension OnboardingLikingReactor {
    func getOnboardingPlaceReactor() -> OnboardingPlaceReactor {
        return OnboardingPlaceReactor(initialState: .init())
    }
}


// MARK: OnboardingLikingViewController

func presentOnboardingLikingViewController(at reactor: OnboardingPlaceReactor) {
        let onboardingPlaceViewController = OnboardingPlaceViewController()
        onboardingPlaceViewController.reactor = reactor
        navigationController?.pushViewController(onboardingPlaceViewController, animated: true)
}

func bindIsPresentOnboardingPlace(from reactor: OnboardingLikingReactor) {
        reactor.state
            .map { $0.isPresentOnboardingPlace }
            .distinctUntilChanged()
            .filter { $0 }
            .map { _ in reactor.getOnboardingPlaceReactor() }
            .bind(onNext: presentOnboardingLikingViewController)
            .disposed(by: disposeBag)
}
```

##

2022-08-02 02:23 UTC, leeinae approved these changes

2022-08-02 02:23 UTC, leeinae commented on JYP-iOS/JYP-iOS/Sources/Presenter/NavigationBar/NavigationBarViewController.swift
> +    func setNavigationBarTitleFont(_ font: UIFont?)
아하아하 .. 납득 완입니다

2022-08-02 02:23 UTC, leeinae commented on JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPButton.swift
> +class JYPButton: UIButton {
넵 알겠습니다!

2022-08-02 02:23 UTC, leeinae commented
예시 확인했습니다 :) 감사합니다

2022-08-02 02:28 UTC, merged